# 欢迎使用 Jekyll!
#
# 这个配置文件用于设置影响整个网站的设置，
# 这些值通常只需要设置一次，之后很少需要编辑。
# 由于技术原因，当你使用 `jekyll serve` 时，此文件不会自动重新加载。
# 如果你更改了此文件，请重启服务器进程。

# 主题设置
#
# 查看文档以确定你应该使用 `theme` 还是 `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

theme: minimal-mistakes-jekyll  # 或者使用 remote_theme
remote_theme: mmistakes/minimal-mistakes@4.24.0  # 如果使用远程主题
minimal_mistakes_skin    : "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# 网站设置
locale                   : "zh-CN"
rtl                      : # true, false (默认) # 将页面方向改为从右到左，用于RTL语言
title                    : "HUHA的茅屋"
title_separator          : "-"
subtitle                 : "一间简陋的草房，住着一颗不安的心。" # 显示在网站标题下方的标语
name                     : "HUHA"
description              : "一间简陋的草房，住着一颗不安的心。"
url                      : "https://github.com/HUHAGE/huhawebsite" # 你的网站基础主机名和协议，例如 "https://mmistakes.github.io"
baseurl                  : "" # 你的网站子路径，例如 "/blog"
repository               : "HUHAGE/huhawebsite" # GitHub 用户名/仓库名，例如 "mmistakes/minimal-mistakes"
teaser                   : "/assets/images/default-teaser.png"  # 设置默认的预览图片
logo                     : "/assets/images/logo.png"
masthead_title           : # 覆盖显示在页眉的网站标题，使用 " " 则不显示标题
breadcrumbs              : # true, false (默认)
words_per_minute         : 200
enable_copy_code_button  : true # true, false (默认) 允许复制代码
copyright                : # 版权名称，默认使用网站标题
copyright_url            : # 版权URL，默认使用网站URL
comments:
  provider               : # false (默认), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "giscus", "custom"
  disqus:
    shortname            : # 访问 https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname- 获取
  discourse:
    server               : # 访问 https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 获取，例如: meta.discourse.org
  facebook:
    # 访问 https://developers.facebook.com/docs/plugins/comments 获取
    appid                :
    num_posts            : # 5 (默认)
    colorscheme          : # "light" (默认), "dark"
  utterances:
    theme                : # "github-light" (默认), "github-dark"
    issue_term           : # "pathname" (默认)
  giscus:
    repo_id              : # 在 https://giscus.app 设置时显示
    category_name        : # 分类的完整文本名称
    category_id          : # 在 https://giscus.app 设置时显示
    discussion_term      : # "pathname" (默认), "url", "title", "og:title"
    reactions_enabled    : # '1' 启用 (默认), '0' 禁用
    theme                : # "light" (默认), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"
    strict               : # 1 启用, 0 禁用 (默认)
    input_position       : # "top", "bottom" # 评论输入框将放置在评论的上方或下方
    emit_metadata        : # 1 启用, 0 禁用 (默认)
    lang                 : # "en" (默认)
    lazy                 : # true, false # 评论加载将延迟到用户滚动到评论容器附近
  staticman:
    branch               : # "master"
    endpoint             : # "https://{your Staticman v3 API}/v3/entry/github/"
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # 空白 (默认) 使用 feed.xml
  hide                   : # true, false (默认)
search                   : true # true, false (默认)
search_full_content      : true # true, false (默认)
search_provider          : # lunr (默认), algolia, google
lunr:
  search_within_pages    : true # true, false (默认)
algolia:
  application_id         : # 你的应用ID
  index_name             : # 你的索引名称
  search_only_api_key    : # 你的搜索专用API密钥
  powered_by             : # true (默认), false
google:
  search_engine_id       : # 你的搜索引擎ID
  instant_search         : # false (默认), true
# SEO 相关
google_site_verification :
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :

# 社交分享
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter 默认站点图片
# 用于指定社交档案
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # 个人或组织 (默认为个人)
  name                   : # 如果用户或组织名称与站点名称不同
  links: # 社交媒体链接数组

# 分析统计
analytics:
  provider               : "google" # false (默认), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          :
    anonymize_ip         : true # true, false (默认)

# 站点作者
author:
  name             : "HUHA"
  avatar           : "/assets/images/huha-avatar.png"
  bio              : "江湖迷途小书童，小小凡人。"
  location         : "四川 - 成都"
  #email            : "wsyhok@126.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:wsyhok@126.com"
    - label: "CSDN"
      icon: "fas fa-fw fa-link"
      url: "https://blog.csdn.net/wsyhok"
    - label: "Gitee"
      icon: "fab fa-fw fa-github"
      url: "https://gitee.com/huhage"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/" 注释掉的不会在页面展示

# 站点页脚
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url:
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url:

# 读取文件
include:
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # 忽略 Minimal Mistakes /docs
  - /test # 忽略 Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# 转换设置
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown 处理
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# 输出设置
permalink: /:categories/:title/
timezone: Asia/Shanghai  # 设置时区

# 使用 jekyll-paginate 进行分页
paginate: 5 # 显示的文章数量
paginate_path: /page:num/

# 使用 jekyll-paginate-v2 进行分页
# 查看 https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
# 获取配置详情
pagination:
  # 设置 enabled 为 true 以使用 paginate v2
  # enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2

# 插件 (之前称为 gems)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# 模拟 GitHub Pages 的 --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# 归档
#  类型
#  - GitHub Pages 兼容的使用 Liquid 构建的归档页面 ~> type: liquid (默认)
#  - Jekyll Archives 插件归档页面 ~> type: jekyll-archives
#  路径 (示例)
#  - 使用 Liquid 方法时归档页面应该存在于路径中，否则可能会导致链接失效
#    (特别是在启用面包屑导航时)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML 压缩
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# 默认值
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
      header:
        show_overlay_excerpt: true
  
  # _books
  - scope:
      path: ""
      type: books
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
      
  # _essays
  - scope:
      path: ""
      type: essays
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

# 添加新的集合
collections:
  books:
    output: true
    permalink: /:collection/:path/
  essays:
    output: true
    permalink: /:collection/:path/

# 确保包含_pages目录
include:
  - _pages

